/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  84532: {
    MarketController: {
      address: "0x64949fedafb776922e18e0908df50db789fdfbc8",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_vaultAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "_usdcAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "_ooAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "_bondAddress",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "IDENTIFIER",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "bets",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "principal",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "weight",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "side",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "claimed",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "bondCurrency",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IERC20",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "claim",
          inputs: [
            {
              name: "_poolId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "claimCreatorRewards",
          inputs: [
            {
              name: "_poolId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createPool",
          inputs: [
            {
              name: "_question",
              type: "string",
              internalType: "string",
            },
            {
              name: "_duration",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_initialSeed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getPoolMetrics",
          inputs: [
            {
              name: "_poolId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "currentTotalYield",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "estimatedWinnerPrize",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "estimatedCreatorFee",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "oo",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract OptimisticOracleV2Interface",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "placeBet",
          inputs: [
            {
              name: "_poolId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_side",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "_amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "poolCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "pools",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "creator",
              type: "address",
              internalType: "address",
            },
            {
              name: "question",
              type: "string",
              internalType: "string",
            },
            {
              name: "endTime",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalShares",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalPrincipal",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "creatorPrincipal",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "resolved",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "outcome",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "requestSubmitted",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "requestTime",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "ancillaryData",
              type: "bytes",
              internalType: "bytes",
            },
            {
              name: "yesPrincipal",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "noPrincipal",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalYesWeight",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalNoWeight",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "finalTotalYield",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "requestResolution",
          inputs: [
            {
              name: "_poolId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "settleResolution",
          inputs: [
            {
              name: "_poolId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "usdc",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IERC20",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "vault",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract NoLossVault",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "BetPlaced",
          inputs: [
            {
              name: "poolId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "user",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "side",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "weight",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OracleRequested",
          inputs: [
            {
              name: "poolId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PoolCreated",
          inputs: [
            {
              name: "poolId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "question",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "endTime",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PoolResolved",
          inputs: [
            {
              name: "poolId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "outcome",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
            {
              name: "totalYield",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 35108151,
    },
  },
  11155111: {
    MarketController: {
      address: "0x6f81048e1988c85c99316472c94d2cf7a7eac21d",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_vaultAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "_usdcAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "_ooAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "_bondAddress",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "IDENTIFIER",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "bets",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "principal",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "weight",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "side",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "claimed",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "bondCurrency",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IERC20",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "claim",
          inputs: [
            {
              name: "_poolId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "claimCreatorRewards",
          inputs: [
            {
              name: "_poolId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createPool",
          inputs: [
            {
              name: "_question",
              type: "string",
              internalType: "string",
            },
            {
              name: "_duration",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_initialSeed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getPoolMetrics",
          inputs: [
            {
              name: "_poolId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "currentTotalYield",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "estimatedWinnerPrize",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "estimatedCreatorFee",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "oo",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract OptimisticOracleV2Interface",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "placeBet",
          inputs: [
            {
              name: "_poolId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_side",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "_amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "poolCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "pools",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "creator",
              type: "address",
              internalType: "address",
            },
            {
              name: "question",
              type: "string",
              internalType: "string",
            },
            {
              name: "endTime",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalShares",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalPrincipal",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "creatorPrincipal",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "resolved",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "outcome",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "requestSubmitted",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "requestTime",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "ancillaryData",
              type: "bytes",
              internalType: "bytes",
            },
            {
              name: "yesPrincipal",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "noPrincipal",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalYesWeight",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalNoWeight",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "finalTotalYield",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "requestResolution",
          inputs: [
            {
              name: "_poolId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "settleResolution",
          inputs: [
            {
              name: "_poolId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "usdc",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IERC20",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "vault",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract NoLossVault",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "BetPlaced",
          inputs: [
            {
              name: "poolId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "user",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "side",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "weight",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OracleRequested",
          inputs: [
            {
              name: "poolId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PoolCreated",
          inputs: [
            {
              name: "poolId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "question",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "endTime",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PoolResolved",
          inputs: [
            {
              name: "poolId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "outcome",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
            {
              name: "totalYield",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 9865502,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
