/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  84532: {
    MarketController: {
      address: "0xe5a5148fea475d65e0542e6c111073e06ffb14d5",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_vaultAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "_usdcAddress",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "bets",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "principal",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "weight",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "side",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "claimed",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "claim",
          inputs: [
            {
              name: "_poolId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "claimCreatorRewards",
          inputs: [
            {
              name: "_poolId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createPool",
          inputs: [
            {
              name: "_question",
              type: "string",
              internalType: "string",
            },
            {
              name: "_duration",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_initialSeed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getPoolMetrics",
          inputs: [
            {
              name: "_poolId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "currentTotalYield",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "estimatedWinnerPrize",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "estimatedCreatorFee",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "placeBet",
          inputs: [
            {
              name: "_poolId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_side",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "_amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "poolCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "pools",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "creator",
              type: "address",
              internalType: "address",
            },
            {
              name: "question",
              type: "string",
              internalType: "string",
            },
            {
              name: "endTime",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalShares",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalPrincipal",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "creatorPrincipal",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "resolved",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "outcome",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "yesPrincipal",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "noPrincipal",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalYesWeight",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalNoWeight",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "finalTotalYield",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "resolvePool",
          inputs: [
            {
              name: "_poolId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_outcome",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "usdc",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IERC20",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "vault",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract NoLossVault",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "BetPlaced",
          inputs: [
            {
              name: "poolId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "user",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "side",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "weight",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PoolCreated",
          inputs: [
            {
              name: "poolId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "question",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "endTime",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PoolResolved",
          inputs: [
            {
              name: "poolId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "outcome",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
            {
              name: "totalYield",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 34681992,
    },
  },
  11155111: {
    MarketController: {
      address: "0x0824cae8116a58282e8303abaa4a5c00aeb02c2d",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_vaultAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "_usdcAddress",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "bets",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "principal",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "weight",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "side",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "claimed",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "claim",
          inputs: [
            {
              name: "_poolId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "claimCreatorRewards",
          inputs: [
            {
              name: "_poolId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createPool",
          inputs: [
            {
              name: "_question",
              type: "string",
              internalType: "string",
            },
            {
              name: "_duration",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_initialSeed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getPoolMetrics",
          inputs: [
            {
              name: "_poolId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "currentTotalYield",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "estimatedWinnerPrize",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "estimatedCreatorFee",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "placeBet",
          inputs: [
            {
              name: "_poolId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_side",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "_amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "poolCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "pools",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "creator",
              type: "address",
              internalType: "address",
            },
            {
              name: "question",
              type: "string",
              internalType: "string",
            },
            {
              name: "endTime",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalShares",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalPrincipal",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "creatorPrincipal",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "resolved",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "outcome",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "yesPrincipal",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "noPrincipal",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalYesWeight",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalNoWeight",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "finalTotalYield",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "resolvePool",
          inputs: [
            {
              name: "_poolId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_outcome",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "usdc",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IERC20",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "vault",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract NoLossVault",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "BetPlaced",
          inputs: [
            {
              name: "poolId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "user",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "side",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "weight",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PoolCreated",
          inputs: [
            {
              name: "poolId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "question",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "endTime",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PoolResolved",
          inputs: [
            {
              name: "poolId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "outcome",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
            {
              name: "totalYield",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 9787329,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
